### ISSUE TITLE
Remove hardcoded nubis domain

### ISSUE THREAD

**Issue by limed** [nubisproject/nubis-docker-deploy#66]
Public state has nubis domain hardcoded we should have some sort of option to set a domain

**Comment by tinnightcap** [comment]
The only place where the domain seems to be hard-coded is in the lookup to the state bucket. I am not sure how to get and use the domain from the state bucket without knowing where to find the state bucket. I am open to suggestions or clarification if this is not what you were referring to.

**Comment by tinnightcap** [comment]
I just saw nubisproject/nubis-ctl/issues/31 which would address the concern I believe and is a good idea.
